apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  replicas: 1
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: varundora/userservice:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 8081